### PR TITLE
Added an instruction for how to setup locally

### PR DESCRIPTION
**Pull request by iambenkay**
removed Procfile and customised package.json to work well in place of it
for heroku

### CODE REVIEW

**Comment by iambenkay** [comment]
@SlyCreator This is it

**Comment by SlyCreator** [comment]
@iambenkay  the file you remove will cause a bug in the heroku server..Heroku was suppose to read that file.

**Comment by iambenkay** [comment]
Procfiles are not necessary in node.js applications. The `npm start` script serves as the runtime for the dyno. That's why I setup `package.json` start script

**Comment by SlyCreator** [comment]
I have the app in production already..that how it was configured..meanwhile node works with index.js or server.js

**Comment by iambenkay** [comment]
I know that node works with both server.js and index.js. I just wanted a more conventional style

**Pull request merged**
